server:
  port: 8080
spring:
  application:
    name: "parking"
  r2dbc:
    name: parking
    username: root
    password: 12345678
    url: r2dbc:postgresql://parking.ciusywni3ifc.us-east-1.rds.amazonaws.com:5432/parking?sslmode=require
    #pool:
      #max-size: 10
      #max-acquire-time: 10s
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus" # para que sirve esto?
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"