spring:
  r2dbc:
    name: ${NAME_DATABASE:parking}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:12345}
    url: ${DATASOURCE_URL:r2dbc:postgresql://localhost:5433/postgres}
    #pool:
      #max-size: 10
      #max-acquire-time: 10s
management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

cors:
  allowed-origins: "*"

endpoint:
  micro:
    user: ${ENDPOINT_USER:http://localhost:8080}

variable:
  limit:
    parkings: ${LIMIT_PARKINGS_BY_LOCATION:2}


resilience:
  communication:
    max-attempts: 3
    backoff-interval: 1