kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress
  namespace: {{ .Values.namespaces }}
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: user-api
                port:
                  number: 8081
            path: /api/users(/|$)(.*)
            pathType: Prefix
          - backend:
              service:
                name: parking-api
                port:
                  number: 8090
            path: /api/parkings(/|$)(.*)
            pathType: Prefix
#status:
#  loadBalancer:
#    ingress:
#      - hostname: 11.elb.us-east-1.amazonaws.com