kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespaces }}
  labels:
    app: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.servers.port }}
      targetPort: {{ .Values.servers.port }}